//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreData
    {
        public int Vers { get; set; }
        public Nullable<System.DateTime> FatIni { get; set; }
        public Nullable<System.DateTime> FatFim { get; set; }
    }
}
