//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalhesPedido
    {
        public int NroPedido { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<int> Qtde { get; set; }
        public Nullable<double> Preco { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
